language: python

python:
 - "3.5"

install:
 - pip install python-coveralls
 - pip install coverage
 - pip install nose

 - pip3 install colored


script:
 - pytest
 - coverage run --source=mypkg setup.py test

after_success:
 - coveralls
